# https://dependabot-gitlab.gitlab.io/config/configuration.html
version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "org.elasticsearch*"
    #pull-request-branch-name:
      #separator: 'default: "-"'
      #prefix: 'default: "dependabot"'
      #max-length: 40
    #allow:
    #  - dependency-type: 'default: "direct"'
    #open-pull-requests-limit: 'default: 5'
    #open-security-pull-requests-limit: 'default: 10'
    #versioning-strategy: 'default: "auto"'
    #rebase-strategy: 'default: "auto"'
    #auto-merge: 'default: false'
    #fork: 'default: false'
    #vendor: 'default: false'
    #insecure-external-code-execution: 'default: false'
    #registries: 'default: "*"'
    #labels: 'default: none'
    #commit-message: 'default: none'
    #milestone: 'default: none'
    #ignore: 'default: none'
    #assignees: 'default: none'
    #reviewers: 'default: none'
    #approvers: 'default: none'
    #updater-options: 'default: none'
    #vulnerability-alerts: 'default: enabled: true, confidential: true'
    #disable-mr-creation: 'default: false'
