ARG ES_VERSION

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}

COPY search-guard-flx-elasticsearch-plugin-trivy.zip /plugin.zip
RUN elasticsearch-plugin install --batch file:///plugin.zip
